spring.application.name=backend

# Database Connection
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_biblioteca}
spring.datasource.username=${DB_USER:trabalho_menolli}
spring.datasource.password=${DB_PASS:senha_menolli}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Multa por dia de atraso na devolução (por livro)
biblioteca.multa.valor-por-dia=2.00

# Execução automática do script de carga de dados
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

